demo/app/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from .views import CompanyEditView, CompanyListView, PersonEditView, PersonListView, WatchlistView

app_name = "demo"
urlpatterns = [
    path("", PersonListView.as_view(), name="app_person_changelist"),
    path(
        "person/edit/<int:pk>/",
        PersonEditView.as_view(success_url=reverse_lazy("demo:app_person_changelist")),
        name="app_person_change",
    ),
    path("company/", CompanyListView.as_view(), name="app_company_changelist"),
    path(
        "company/edit/<int:pk>/",
        CompanyEditView.as_view(success_url=reverse_lazy("demo:app_company_changelist")),
        name="app_company_change",
    ),
    path("watchlist/", WatchlistView.as_view(), name="watchlist"),
    path("login/", LoginView.as_view(next_page="demo:app_person_changelist"), name="login"),
    path("logout/", LogoutView.as_view(next_page="demo:app_person_changelist"), name="logout"),
]

demo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mizdb_watchlist/", include("mizdb_watchlist.urls")),
    path("", include("app.urls")),
]

demo/app/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "Persons"
        ordering = ["last_name", "first_name"]


class Company(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ["name"]

demo/app/views.py
from django import forms, views

from mizdb_watchlist.views import WatchlistMixin, WatchlistViewMixin

from .models import Company, Person


class PersonListView(WatchlistMixin, views.generic.ListView):
    queryset = Person.objects.all()
    template_name = "changelist.html"


class CompanyListView(WatchlistMixin, views.generic.ListView):
    queryset = Company.objects.all()
    template_name = "changelist.html"


class PersonEditView(views.generic.UpdateView):
    model = Person
    fields = forms.ALL_FIELDS
    template_name = "edit.html"


class CompanyEditView(views.generic.UpdateView):
    model = Company
    fields = forms.ALL_FIELDS
    template_name = "edit.html"


class WatchlistView(WatchlistViewMixin, views.generic.TemplateView):
    template_name = "watchlist.html"

demo/app/templates/base.html
<!doctype html>
{% load static mizdb_watchlist %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MIZDB Watchlist Demo</title>
    <link href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootswatch/dist/flatly/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.js' %}"></script>
    {% block extrahead %}{% endblock extrahead %}
</head>
<body class="container">
<nav class="navbar navbar-expand">
    <span class="navbar-brand">Watchlist Demo</span>
    <ul class="navbar-nav w-100">
        <li class="nav-item"><a href="{% url 'demo:app_person_changelist' %}" class="nav-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
            Person Changelist
        </a></li>
        <li class="nav-item"><a href="{% url 'demo:app_company_changelist' %}" class="nav-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
            Company Changelist
        </a></li>
        <li class="nav-item">{% watchlist_link 'demo:watchlist' %}</li>
        <li class="nav-item ms-auto">
            {% if view.request.user.is_authenticated %}
                <form method="POST" action="{% url 'demo:logout' %}">
                    {% csrf_token %}
                    <button class="nav-link btn" type="submit">Logout</button>
                </form>
            {% else %}
                <a class="nav-link" href="{% url 'demo:login' %}">Login</a>
            {% endif %}
        </li>
    </ul>
</nav>
{% block content %}
{% endblock content %}
</body>
</html>

demo/app/templates/changelist.html
{% extends "base.html" %}
{% load static mizdb_watchlist %}

{% block extrahead %}
    <script src="{% static 'mizdb_watchlist/js/watchlist.js' %}"></script>
    <script src="{% static 'mizdb_watchlist/js/watchlist_init.js' %}"></script>
    <link rel="stylesheet" href="{% static 'mizdb_watchlist/css/watchlist_toggle.css' %}">
{% endblock extrahead %}

{% block content %}
{% csrf_token %}
<h4>Person Changelist</h4>
<ul class="list-group list-group-flush">
{% for person in object_list %}
    <li class="list-group-item list-group-item-action">
        <div class="d-flex justify-content-between">
            <a href="{% url 'demo:app_person_change' pk=person.pk %}" class="my-auto">{{ person }}</a>
            {% toggle_button view.request person on_watchlist=person.on_watchlist classes='btn btn-link text-decoration-none' %}
        </div>
    </li>
{% empty %}
    <li>No Person objects!</li>
{% endfor %}
</ul>
{% endblock content %}

demo/app/templates/edit.html
{% extends "base.html" %}
{% load static mizdb_watchlist %}
{% block extrahead %}
    <script src="{% static 'mizdb_watchlist/js/watchlist.js' %}"></script>
    <script src="{% static 'mizdb_watchlist/js/watchlist_init.js' %}"></script>
    <link rel="stylesheet" href="{% static 'mizdb_watchlist/css/watchlist_toggle.css' %}">
{% endblock extrahead %}

{% block content %}
<h4>Edit Person</h4>
<h5>{{ object }} {% toggle_button view.request object classes='btn btn-link text-decoration-none' %}</h5>
<form method="post">{% csrf_token %}
    {% for field in form %}
    <div class="row mb-3 ms-3">
        <label for="{{ field.id_for_label }}" class="col-form-label col-2">{{ field.label }}</label>
        <div class="col-10">
            <input class="form-control" type="text" id="{{ field.id }}" name="{{ field.name }}" value="{{ field.value }}">
        </div>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock content %}

demo/app/templates/watchlist.html
{% extends "base.html" %}
{% load static %}

{% block extrahead %}
    <script src="{% static 'mizdb_watchlist/js/watchlist.js' %}"></script>
    <script src="{% static 'mizdb_watchlist/js/watchlist_init.js' %}"></script>
{% endblock %}

{% block content %}
    <h3>Watchlist {% if view.request.user.is_authenticated %}(Model){% else %}(Session){% endif %}</h3>
    {% include "mizdb_watchlist/watchlist.html" %}
{% endblock content %}