src/mizdb_watchlist/urls.py
from django.urls import path

from mizdb_watchlist.views import watchlist_remove, watchlist_remove_all, watchlist_toggle

app_name = "watchlist"
urlpatterns = [
    path("remove/", watchlist_remove, name="remove"),
    path("remove_all/", watchlist_remove_all, name="remove_all"),
    path("toggle/", watchlist_toggle, name="toggle"),
]

src/mizdb_watchlist/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _


class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.IntegerField(verbose_name=_("Object ID"))
    object_repr = models.CharField(max_length=200, verbose_name=_("Object representation"))
    time_added = models.DateTimeField(auto_now_add=True, verbose_name=_("Added at"))

    def __str__(self):
        return f"{self.content_type.name}: {self.object_repr}"  # pragma: no cover

    class Meta:
        ordering = ["user", "content_type", "time_added"]
        verbose_name = _("Watchlist Item")
        verbose_name_plural = _("Watchlist Items")

src/mizdb_watchlist/views.py
from collections import OrderedDict

from django.apps import apps
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseBadRequest, JsonResponse
from django.urls import NoReverseMatch, reverse
from django.views.decorators.csrf import csrf_protect
from django.views.generic.base import ContextMixin

from mizdb_watchlist.manager import ANNOTATION_FIELD, get_manager

ON_WATCHLIST_VAR = ANNOTATION_FIELD


def _get_model_object(model_label, pk):
    model = apps.get_model(model_label)
    return model.objects.get(pk=pk)


class WatchlistViewMixin(ContextMixin):
    """A view mixin that adds template context items for displaying the watchlist."""

    def get_watchlist(self, request, prune=True):
        """Return the watchlist in dictionary form for the given request."""
        manager = get_manager(request)
        if prune:
            manager.prune()
        return manager.as_dict()

    def get_watchlist_context(self, request):
        """Return template context items for display the watchlist."""
        context = {}
        watchlist = {}
        for model_label, watchlist_items in self.get_watchlist(request).items():
            model_items = []
            try:
                model = apps.get_model(model_label)
            except LookupError:
                continue

            # Add the URL to the change page of each item:
            for watchlist_item in watchlist_items:
                try:
                    watchlist_item["object_url"] = self.get_object_url(request, model, watchlist_item["object_id"])
                except NoReverseMatch:
                    continue
                watchlist_item["model_label"] = model_label
                watchlist_item["object_repr"] = self.get_object_text(
                    request, model, watchlist_item["object_id"], watchlist_item["object_repr"]
                )
                model_items.append(watchlist_item)

            if model_items:
                if changelist_url := self.get_changelist_url(request, model):
                    changelist_url = f"{self.get_changelist_url(request, model)}?{ON_WATCHLIST_VAR}=True"
                data = {"model_items": model_items, "changelist_url": changelist_url, "model_label": model_label}
                watchlist[model._meta.verbose_name.capitalize()] = data
        context["watchlist"] = OrderedDict(sorted(watchlist.items()))
        return context

    def _get_url_for_watchlist_link(self, request, viewname, args=None, kwargs=None):
        if app_name := request.resolver_match.app_name:
            viewname = f"{app_name}:{viewname}"
        try:
            return reverse(viewname, args=args, kwargs=kwargs, current_app=request.resolver_match.namespace)
        except NoReverseMatch:
            # Fail silently if the name cannot be reversed. The template will
            # then simply not render any links.
            return ""

    def get_object_url(self, request, model, pk):
        """
        Return the URL to the change page of the object described by the given
        model and primary key.
        """
        viewname = f"{model._meta.app_label}_{model._meta.model_name}_change"
        return self._get_url_for_watchlist_link(request, viewname, args=[pk])

    def get_changelist_url(self, request, model):
        """Return the URL to the changelist of the given model."""
        viewname = f"{model._meta.app_label}_{model._meta.model_name}_changelist"
        return self._get_url_for_watchlist_link(request, viewname)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_watchlist_context(self.request))  # noqa
        return context

    def get_object_text(self, request, model, pk, object_repr=""):
        """
        Return a text to be displayed on the overview for the watchlist item
        given by the model and object id.
        """
        return object_repr


def annotate_view_queryset(request, queryset):
    """
    Add an 'on_watchlist' attribute to each object in the given queryset that
    denotes whether the object is on a watchlist. If ``ON_WATCHLIST_VAR`` is
    present in the request GET parameters, filter the queryset to only include
    items that are on the watchlist.
    """
    manager = get_manager(request)
    queryset = manager.annotate_queryset(queryset)
    if ON_WATCHLIST_VAR in request.GET:
        queryset = manager.filter(queryset)
    return queryset


class WatchlistMixin:
    """
    A mixin that adds annotations and filtering specific to the watchlist to
    the view's queryset.

    If ``ON_WATCHLIST_VAR`` (defaults to: ``on_watchlist``) is present in the
    request GET parameters, the queryset will be filtered to only include
    objects that are currently on the user's watchlist.

    Set ``add_watchlist_annotations`` to ``False`` to skip adding annotations
    and disable filtering.

    Add this mixin to your list views for models that use the watchlist.
    """

    add_watchlist_annotations = True

    def get_queryset(self):
        queryset = super().get_queryset()  # noqa
        if self.add_watchlist_annotations:
            queryset = annotate_view_queryset(self.request, queryset)  # noqa
        return queryset


@csrf_protect
def watchlist_toggle(request):
    """
    Add an object to the watchlist, or remove an object if it already exists on
    the watchlist.

    Used on the change pages of objects.
    """
    try:
        pk = int(request.POST["object_id"])
        model_label = request.POST["model_label"]
    except (KeyError, ValueError):
        return HttpResponseBadRequest()
    try:
        obj = _get_model_object(model_label, pk)
    except (LookupError, ObjectDoesNotExist):
        on_watchlist = False
    else:
        manager = get_manager(request)
        on_watchlist = manager.toggle(obj)
    return JsonResponse({"on_watchlist": on_watchlist})


@csrf_protect
def watchlist_remove(request):
    """
    Remove an object from the watchlist.

    Used on the watchlist overview to remove items.
    """
    try:
        pk = int(request.POST["object_id"])
        model_label = request.POST["model_label"]
    except (KeyError, ValueError):
        return HttpResponseBadRequest()
    try:
        manager = get_manager(request)
        manager.remove(_get_model_object(model_label, pk))
    except (LookupError, ObjectDoesNotExist):
        pass
    return JsonResponse({})


@csrf_protect
def watchlist_remove_all(request):
    """Remove all objects of a given model from the watchlist."""
    try:
        model = apps.get_model(request.POST["model_label"])
    except (KeyError, LookupError):
        return HttpResponseBadRequest()
    get_manager(request).remove_model(model)
    return JsonResponse({})

src/mizdb_watchlist/templates/mizdb_watchlist/toggle_button.html
{% load i18n %}
{% if toggle_url %}
<button type="button"
        class="watchlist-btn watchlist-toggle-btn {{ classes }} {% if on_watchlist %}on-watchlist{% endif %}"
        title="{% translate 'Toggle watchlist' %}"
        data-url="{{ toggle_url }}" data-object-id="{{ object_id }}" data-model-label="{{ model_label }}"
>{% include 'mizdb_watchlist/watchlist_icon.svg' %}{% if text %}{{ text }}{% endif %}</button>
{% endif %}

src/mizdb_watchlist/templates/mizdb_watchlist/watchlist.html
{% load static i18n %}
{% csrf_token %}

<div id="watchlist">
    {% for model_name, watchlist_data in watchlist.items %}
    <div id="{{model_name}}-watchlist" class="model-watchlist-container mb-3 p-3 border rounded">
        <div class="d-flex justify-content-between border-bottom">
            <div class="d-flex justify-content-between">
                <h2 class="watchlist-model-heading">{{ model_name }}</h2>
                {% if watchlist_data.changelist_url %}
                    <a class="btn btn-link my-auto watchlist-btn watchlist-changelist-btn" href="{{ watchlist_data.changelist_url }}">{% trans 'Changelist' %}</a>
                {% endif %}
            </div>
            <button class="btn btn-outline-danger my-2 watchlist-btn watchlist-remove-all-btn"
                    data-url="{% url 'watchlist:remove_all' %}"
                    data-model-label="{{ watchlist_data.model_label }}"
                    title="{% blocktranslate %}Remove all {{ model_name }} watchlist items{% endblocktranslate %}"
            >{% trans 'Remove all' %}</button>
        </div>
        <ul class="list-group list-group-flush watchlist-items-list">
            {% for watchlist_item in watchlist_data.model_items %}
            <li class="list-group-item list-group-item-action d-flex justify-content-between watchlist-item">
                {% if watchlist_item.object_url %}
                    <a href="{{ watchlist_item.object_url }}" class="text-decoration-none my-auto">{{ watchlist_item.object_repr }}</a>
                {% else %}
                    <span class="my-auto">{{ watchlist_item.object_repr }}</span>
                {% endif %}
                <button class="btn btn-outline-danger border-0 watchlist-btn watchlist-remove-btn" title="{% translate 'Remove from watchlist' %}" data-url="{% url 'watchlist:remove' %}" data-object-id="{{ watchlist_item.object_id }}" data-model-label="{{ watchlist_item.model_label }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                </button>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
    <p id="empty-watchlist" style="display: {% if watchlist %}none{% else %}block{% endif %};">{% translate 'There are no items on your watchlist.' %}</p>
</div>

src/mizdb_watchlist/templates/mizdb_watchlist/watchlist_link.html
{% load i18n %}
{% url view_name as watchlist_url %} {# {% url ... as var %} will not raise an error if the URL name cannot be reversed #}
<a class="nav-link watchlist-link" href="{{ watchlist_url }}">
  {% if icon %}<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>{% endif %}
  {% trans 'My Watchlist' %}
</a>